name: mini_project
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  auth_buttons: ^1.0.1+4
  countup: ^0.1.4
  curved_navigation_bar: ^1.0.3
  firebase_auth: ^4.6.2
  firebase_database: ^10.2.2
  flutter:
    sdk: flutter
  flutter_spinkit: ^5.2.0
  google_sign_in: ^6.1.4
  http: ^1.0.0
  intl: ^0.18.1
  mailer: ^6.0.1
  pdf: ^3.10.4
  permission_handler: ^10.3.0
  printing: ^5.11.0
  provider: ^6.0.5
  qr_flutter: ^4.1.0
  qrscan: ^0.3.3
  quickalert: ^1.0.1
  razorpay_flutter: ^1.3.5
  syncfusion_flutter_datagrid: ^21.2.9
  table_calendar: ^3.0.9
  uuid: ^3.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.gif
    - assets/images/Attendence.png
    - assets/images/logo.png
    - assets/images/login.png
